#!/bin/bash
# Frontend deployment script
# Fetches configuration from OpenTofu outputs, builds, and deploys to S3/CloudFront

set -e

# Configuration
ENVIRONMENT="${ENVIRONMENT:-dev}"
REGION="${AWS_REGION:-us-east-1}"

echo "🚀 Deploying Frontend"
echo "   Environment: ${ENVIRONMENT}"
echo "   Region: ${REGION}"
echo ""

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# OpenTofu environment directory
TOFU_DIR="$SCRIPT_DIR/../tofu/application/environments/$ENVIRONMENT"

# ============================================================
# Helper: fetch an OpenTofu output, returning empty on failure
# ============================================================
tofu_output() {
    local key="$1"
    (cd "$TOFU_DIR" && tofu output -raw "$key" 2>/dev/null) || echo ""
}

# ============================================================
# Step 1: Fetch configuration from OpenTofu outputs
# ============================================================
echo "📡 Fetching configuration from OpenTofu outputs..."

USER_POOL_ID=$(tofu_output cognito_user_pool_id)
CLIENT_ID=$(tofu_output cognito_client_id)
COGNITO_DOMAIN=$(tofu_output cognito_domain)
S3_BUCKET=$(tofu_output static_assets_bucket)
CF_DISTRIBUTION=$(tofu_output cloudfront_distribution_id)
APPSYNC_API_URL=$(tofu_output appsync_api_url)
SITE_URL=$(tofu_output site_url)

# ============================================================
# Fallbacks to AWS CLI when OpenTofu outputs are unavailable
# ============================================================
if [ -z "$USER_POOL_ID" ] || [ "$USER_POOL_ID" == "None" ]; then
    POOL_NAME="kernelworx-users-ue1-${ENVIRONMENT}"
    USER_POOL_ID=$(aws cognito-idp list-user-pools --max-results 50 \
        --query "UserPools[?Name=='$POOL_NAME'].Id | [0]" \
        --output text \
        --region "$REGION" 2>/dev/null || echo "")
fi

if [ -z "$CLIENT_ID" ] || [ "$CLIENT_ID" == "None" ]; then
    CLIENT_ID=$(aws cognito-idp list-user-pool-clients \
        --user-pool-id "$USER_POOL_ID" \
        --max-results 1 \
        --query "UserPoolClients[0].ClientId" \
        --output text \
        --region "$REGION" 2>/dev/null || echo "")
fi

if [ -z "$COGNITO_DOMAIN" ] || [ "$COGNITO_DOMAIN" == "None" ]; then
    COGNITO_DOMAIN=$(aws cognito-idp describe-user-pool \
        --user-pool-id "$USER_POOL_ID" \
        --query 'UserPool.CustomDomain' \
        --output text \
        --region "$REGION" 2>/dev/null || echo "")
fi

if [ -z "$S3_BUCKET" ] || [ "$S3_BUCKET" == "None" ]; then
    S3_BUCKET="kernelworx-static-ue1-${ENVIRONMENT}"
fi

if [ -z "$CF_DISTRIBUTION" ] || [ "$CF_DISTRIBUTION" == "None" ]; then
    if [ "$ENVIRONMENT" == "prod" ]; then
        SITE_ALIAS="kernelworx.app"
    else
        SITE_ALIAS="${ENVIRONMENT}.kernelworx.app"
    fi
    CF_DISTRIBUTION=$(aws cloudfront list-distributions \
        --query "DistributionList.Items[?contains(Aliases.Items, '$SITE_ALIAS')].Id | [0]" \
        --output text 2>/dev/null || echo "")
fi

if [ "$ENVIRONMENT" == "prod" ]; then
    SITE_DOMAIN="kernelworx.app"
else
    SITE_DOMAIN="${ENVIRONMENT}.kernelworx.app"
fi

if [ -z "$APPSYNC_API_URL" ] || [ "$APPSYNC_API_URL" == "None" ]; then
    APPSYNC_API_URL="https://api.${SITE_DOMAIN}/graphql"
fi

if [ -z "$SITE_URL" ] || [ "$SITE_URL" == "None" ]; then
    SITE_URL="https://${SITE_DOMAIN}"
fi

# ============================================================
# Validate required values
# ============================================================
if [ -z "$USER_POOL_ID" ] || [ "$USER_POOL_ID" == "None" ]; then
    echo "❌ Error: Could not find Cognito User Pool"
    exit 1
fi

if [ -z "$CLIENT_ID" ] || [ "$CLIENT_ID" == "None" ]; then
    echo "❌ Error: Could not find Cognito App Client"
    exit 1
fi

if [ -z "$CF_DISTRIBUTION" ] || [ "$CF_DISTRIBUTION" == "None" ]; then
    echo "❌ Error: Could not find CloudFront distribution"
    exit 1
fi

# Verify bucket exists
if ! aws s3api head-bucket --bucket "$S3_BUCKET" 2>/dev/null; then
    echo "❌ Error: S3 bucket $S3_BUCKET does not exist"
    exit 1
fi

echo "   User Pool ID: $USER_POOL_ID"
echo "   Client ID: $CLIENT_ID"
echo "   Cognito Domain: $COGNITO_DOMAIN"
echo "   S3 Bucket: $S3_BUCKET"
echo "   CloudFront Distribution: $CF_DISTRIBUTION"
echo "   Site URL: $SITE_URL"
echo "   API Endpoint: $APPSYNC_API_URL"

# ============================================================
# Step 2: Generate .env.production file (used by Vite for builds)
# ============================================================
echo ""
echo "📝 Generating .env.production file..."

cat > .env.production << EOF
# Auto-generated by deploy.sh - $(date)
# AppSync GraphQL API
# VITE_APPSYNC_ENDPOINT is intentionally unset: the deployed app calls
# /graphql same-origin through the site's CloudFront distribution.
VITE_APPSYNC_REGION=${REGION}

# Cognito User Pool
VITE_COGNITO_USER_POOL_ID=${USER_POOL_ID}
VITE_COGNITO_USER_POOL_CLIENT_ID=${CLIENT_ID}
# VITE_COGNITO_DOMAIN is intentionally unset: auth is proxied same-origin at
# root paths (/login, /logout, /oauth2/*); the OAuth domain falls back to the
# site URL. Ephemeral environments set it to the pool prefix domain.

# OAuth Configuration
VITE_OAUTH_REDIRECT_SIGNIN=${SITE_URL}
VITE_OAUTH_REDIRECT_SIGNOUT=${SITE_URL}
EOF

# Also update .env for local dev consistency, keeping the direct endpoints
# that 'vite dev' needs (localhost is not behind CloudFront).
cp .env.production .env
cat >> .env << EOF
# Local 'vite dev' overrides (not used by production builds)
VITE_APPSYNC_ENDPOINT=${APPSYNC_API_URL}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}
EOF

echo "   .env.production file updated"

# ============================================================
# Step 3: Build frontend
# ============================================================
echo ""
echo "🔨 Building frontend..."
npm run build

# ============================================================
# Step 4: Sync to S3
# ============================================================
echo ""
echo "☁️  Uploading to S3..."
aws s3 sync dist "s3://${S3_BUCKET}" --delete --region "$REGION"

# ============================================================
# Step 5: Invalidate CloudFront cache
# ============================================================
echo ""
echo "🔄 Invalidating CloudFront cache..."
INVALIDATION_ID=$(aws cloudfront create-invalidation \
    --distribution-id "$CF_DISTRIBUTION" \
    --paths "/*" \
    --query "Invalidation.Id" \
    --output text)

echo "   Invalidation ID: $INVALIDATION_ID"

# ============================================================
# Done!
# ============================================================
DEPLOY_TIME=$(date '+%Y-%m-%d %H:%M:%S %Z')

echo ""
echo "✅ Deployment complete!"
echo ""
echo "   Site URL: ${SITE_URL}"
echo "   CloudFront invalidation may take 1-2 minutes to complete."
echo "   Deployed at: ${DEPLOY_TIME}"
echo ""
