# KICS configuration file
# Excludes queries that are not applicable or too expensive for this volunteer project

exclude-queries:
  # WAF is too expensive for volunteer/personal budget (~$5/month + $1 per million requests)
  - 1419b4c6-6d5c-4534-9cf6-6a5266085333
  # S3 access logging disabled to minimize storage costs
  - 4552b71f-0a2a-4bc4-92dd-ed7ec1b4674c
  