import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = join(__dirname, '..', '..');
const APPSYNC_MODULE_DIR = join(ROOT_DIR, 'tofu', 'application', 'modules', 'appsync');

interface TemplatefileUse {
    /** The .tf file declaring the templatefile() call. */
    tfFile: string;
    /** Resolver source file loaded through templatefile(). */
    sourceFile: string;
    /** Placeholder names the call site declares (the keys of its vars map). */
    allowedPlaceholders: string[];
}

/** Every .tf file in the AppSync module, including ones added later. */
function moduleTerraformFiles(dir: string): string[] {
    return readdirSync(dir)
        .filter((f) => f.endsWith('.tf'))
        .map((f) => join(dir, f))
        .filter((f) => statSync(f).isFile())
        .sort();
}

/**
 * Where the module's templatefile() calls read from. The bundled directory
 * (`appsync/dist`) is generated by `npm run build:resolvers`, so the guard
 * checks the `js-resolvers` source that developers actually edit.
 */
function resolverSourceDir(): string {
    const variables = readFileSync(join(APPSYNC_MODULE_DIR, 'variables.tf'), 'utf8');
    const match = variables.match(/^\s*js_resolvers_dir\s*=\s*"\$\{path\.module\}\/(\S*?)"\s*$/m);
    if (!match) {
        throw new Error('could not find local.js_resolvers_dir in modules/appsync/variables.tf');
    }
    const bundledDir = join(APPSYNC_MODULE_DIR, match[1]);
    expect(bundledDir.endsWith(join('appsync', 'dist'))).toBe(true);
    return join(dirname(bundledDir), 'js-resolvers');
}

const SOURCE_DIR = resolverSourceDir();

/**
 * Collect every templatefile() call in the module and resolve it to the source
 * file plus the placeholder names it declares. The file list is derived from
 * the Terraform so a fourth templatefile() user is covered automatically.
 */
function templatefileUses(): TemplatefileUse[] {
    const uses: TemplatefileUse[] = [];
    const call = /templatefile\(\s*"\$\{local\.js_resolvers_dir\}\/([^"]+)"\s*,\s*\{([\s\S]*?)\n\s*\}\)/g;

    for (const tfFile of moduleTerraformFiles(APPSYNC_MODULE_DIR)) {
        const content = readFileSync(tfFile, 'utf8');
        for (const match of content.matchAll(call)) {
            const [, fileName, varsBody] = match;
            const allowedPlaceholders = [...varsBody.matchAll(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/gm)].map((m) => m[1]);
            uses.push({
                tfFile: tfFile.slice(ROOT_DIR.length + 1),
                sourceFile: join(SOURCE_DIR, fileName),
                allowedPlaceholders,
            });
        }
    }
    return uses;
}

/**
 * Every `${...}` sequence that templatefile() would try to interpolate, as
 * `line: ${...}`. `$${` is templatefile()'s escape for a literal `${`, so it is
 * skipped (negative lookbehind on the `$`).
 */
function unescapedInterpolations(content: string): string[] {
    return content
        .split('\n')
        .flatMap((lineText, index) =>
            [...lineText.matchAll(/(?<!\$)\$\{[^}]*\}/g)].map(
                (m) => `${index + 1}: ${m[0]}`,
            ),
        );
}

describe('templatefile()-loaded resolvers only interpolate declared placeholders (#570)', () => {
    const uses = templatefileUses();

    it('derives a non-empty list of templatefile()-loaded resolvers from the Terraform', () => {
        // Guards against the guard going vacuous if the HCL shape changes.
        expect(uses.length).toBeGreaterThan(0);
        for (const use of uses) {
            expect(use.allowedPlaceholders.length, `${use.tfFile} declares no placeholders`).toBeGreaterThan(0);
            expect(() => statSync(use.sourceFile)).not.toThrow();
        }
    });

    for (const use of uses) {
        const name = use.sourceFile.slice(ROOT_DIR.length + 1);
        it(`${use.tfFile} keeps ${name} free of unescaped \${...}`, () => {
            const offenders = unescapedInterpolations(readFileSync(use.sourceFile, 'utf8')).filter(
                (offender) =>
                    !use.allowedPlaceholders.includes(offender.slice(offender.indexOf('${') + 2, -1).trim()),
            );
            expect(
                offenders,
                use.tfFile +
                    ' loads ' + name +
                    ' with templatefile(), which interpolates every ${...} sequence in the source as a' +
                    ' Terraform expression and fails every plan/apply with "Invalid expression". Allowed' +
                    ' placeholders: ' + use.allowedPlaceholders.map((p) => '${' + p + '}').join(', ') +
                    '. Escape a literal ${ as $${...}, or load the resolver with file() instead.',
            ).toEqual([]);
        });
    }
});
