import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = join(__dirname, '..', '..');
const APPSYNC_MODULE_DIR = join(ROOT_DIR, 'tofu', 'application', 'modules', 'appsync');

interface TemplatefileUse {
    /** The .tf file declaring the templatefile() call. */
    tfFile: string;
    /** Resolver source file loaded through templatefile(). */
    sourceFile: string;
    /** Placeholder names the call site declares (the keys of its vars map). */
    allowedPlaceholders: string[];
    /** True when the call site declares no placeholders at all. */
    emptyVarsMap: boolean;
}

/** Every .tf file in the AppSync module, including ones added later. */
function moduleTerraformFiles(dir: string): string[] {
    return readdirSync(dir)
        .filter((f) => f.endsWith('.tf'))
        .map((f) => join(dir, f))
        .filter((f) => statSync(f).isFile())
        .sort();
}

/**
 * Where the module's templatefile() calls read from. The bundled directory
 * (`appsync/dist`) is generated by `npm run build:resolvers` with
 * `bundle: true`, so the guard walks the `js-resolvers` sources that get
 * inlined into the bundle.
 */
function resolverSourceDir(): string {
    const variables = readFileSync(join(APPSYNC_MODULE_DIR, 'variables.tf'), 'utf8');
    const match = variables.match(/^\s*js_resolvers_dir\s*=\s*"\$\{path\.module\}\/(\S*?)"\s*$/m);
    if (!match) {
        throw new Error('could not find local.js_resolvers_dir in modules/appsync/variables.tf');
    }
    const bundledDir = join(APPSYNC_MODULE_DIR, match[1]);
    expect(bundledDir.endsWith(join('appsync', 'dist'))).toBe(true);
    return join(dirname(bundledDir), 'js-resolvers');
}

const SOURCE_DIR = resolverSourceDir();

/** Drop HCL comment lines, so comment prose about templatefile() is not counted. */
function stripHclComments(content: string): string {
    return content
        .split('\n')
        .filter((line) => !/^\s*(#|\/\/)/.test(line))
        .join('\n');
}

/** How many templatefile() call sites the module's Terraform declares. */
function templatefileCallCount(): number {
    return moduleTerraformFiles(APPSYNC_MODULE_DIR).reduce(
        (total, tfFile) => total + stripHclComments(readFileSync(tfFile, 'utf8')).split('templatefile(').length - 1,
        0,
    );
}

/**
 * Collect every templatefile() call in the module and resolve it to the source
 * file plus the placeholder names it declares. The file list is derived from
 * the Terraform, so a new templatefile() user is covered automatically.
 */
function templatefileUses(): TemplatefileUse[] {
    const uses: TemplatefileUse[] = [];
    const call = /templatefile\(\s*"([^"]+)"\s*,\s*\{([\s\S]*?)\}/g;

    for (const tfFile of moduleTerraformFiles(APPSYNC_MODULE_DIR)) {
        const content = stripHclComments(readFileSync(tfFile, 'utf8'));
        for (const match of content.matchAll(call)) {
            const [, path, varsBody] = match;
            // `${local.js_resolvers_dir}/batch_get_catalogs_fn.js` -> batch_get_catalogs_fn.js
            const fileName = path.slice(path.lastIndexOf('/') + 1);
            const allowedPlaceholders = [...varsBody.matchAll(/(^|\n)\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/g)].map((m) => m[2]);
            uses.push({
                tfFile: tfFile.slice(ROOT_DIR.length + 1),
                sourceFile: join(SOURCE_DIR, fileName),
                allowedPlaceholders,
                emptyVarsMap: varsBody.trim() === '',
            });
        }
    }
    return uses;
}

/**
 * Every `${...}` sequence templatefile() would try to interpolate, with the
 * placeholder name captured from the same match. `$${` is templatefile()'s
 * escape for a literal `${`, so it is skipped (negative lookbehind on `$`).
 */
function unescapedInterpolations(content: string): { line: number; text: string; name: string }[] {
    return content
        .split('\n')
        .flatMap((lineText, index) =>
            [...lineText.matchAll(/(?<!\$)\$\{([^}]*)\}/g)].map((m) => ({
                line: index + 1,
                text: m[0],
                name: m[1].trim(),
            })),
        );
}

/** Relative `./lib/foo.js` (and `../foo.js`) imports, which esbuild inlines. */
function localImports(file: string): string[] {
    const content = readFileSync(file, 'utf8');
    const specifiers = [...content.matchAll(/(?:from|import)\s+['"](\.[^'"]+)['"]/g)].map((m) => m[1]);
    return specifiers.map((spec) => resolve(dirname(file), spec));
}

/** The entry file plus every local module inlined into its bundle. */
function bundledFiles(entry: string): string[] {
    const seen = new Set<string>();
    const queue = [entry];
    while (queue.length > 0) {
        const file = queue.shift() as string;
        if (seen.has(file)) {
            continue;
        }
        seen.add(file);
        queue.push(...localImports(file));
    }
    return [...seen];
}

describe('templatefile()-loaded resolvers only interpolate declared placeholders (#570)', () => {
    const uses = templatefileUses();

    it('captures every templatefile() call site declared in the module', () => {
        // Guards against the guard going vacuous: a call site whose HCL shape
        // this parser does not understand must fail here, not be skipped.
        expect(uses.length).toBe(templatefileCallCount());
        for (const use of uses) {
            expect(use.sourceFile.endsWith('.js'), `${use.tfFile} has a non-literal resolver filename`).toBe(true);
            expect(() => statSync(use.sourceFile), `${use.tfFile} names a missing ${use.sourceFile}`).not.toThrow();
            expect(
                use.allowedPlaceholders.length > 0 || use.emptyVarsMap,
                `${use.tfFile} declares a placeholders map that could not be parsed`,
            ).toBe(true);
        }
    });

    for (const use of uses) {
        const name = relative(ROOT_DIR, use.sourceFile);
        it(`${use.tfFile} keeps ${name} (and the modules it inlines) free of unescaped \${...}`, () => {
            const files = bundledFiles(use.sourceFile);
            const offenders = files.flatMap((file) =>
                unescapedInterpolations(readFileSync(file, 'utf8'))
                    .filter((match) => !use.allowedPlaceholders.includes(match.name))
                    .map((match) => relative(ROOT_DIR, file) + ':' + match.line + ': ' + match.text),
            );
            expect(
                offenders,
                use.tfFile +
                    ' loads ' + name +
                    ' with templatefile(), which interpolates every ${...} sequence in the source (and in' +
                    ' every local module esbuild inlines into it) as a Terraform expression, failing every' +
                    ' plan/apply with "Invalid expression". Allowed placeholders: ' +
                    (use.allowedPlaceholders.map((p) => '${' + p + '}').join(', ') || '(none)') +
                    '. Escape a literal ${ as $${...}, or load the resolver with file() instead.',
            ).toEqual([]);
        });
    }
});
